
POST https://your-zentao.example.com/zentao/api.php/v1/tokens
Content-Type: 'application/json',

 {
    "account": "your-account",
    "password": "your-password"
}

###
GET https://your-zentao.example.com/zentao/api.php/v1/products/1/bugs?page=2&limit=1
Content-Type: 'application/json',
Token: your-token-here

###

GET https://your-zentao.example.com/zentao/api.php/v1/products/1/bugs?page=1&limit=10&status=openedbyme
Content-Type: 'application/json',
Token: your-token-here
###

GET https://your-zentao.example.com/zentao/api.php/v1/products/1/bugs?page=1&limit=10&status=assigntome
Content-Type: 'application/json',
Token: your-token-here

###
GET https://your-zentao.example.com/zentao/api.php/v1/products/1/bugs?status=assigntome
Content-Type: 'application/json',
Token: your-token-here




###
GET https://your-zentao.example.com/zentao/api-getsessionid.json
Content-Type: 'application/json',
Token: your-token-here

###
GET https://your-zentao.example.com/zentao/user-login.json?account=your-account&password=your-password&zentaosid=your-session-id

######
GET https://your-zentao.example.com/zentao/project-bug-1.json?zentaosid=your-session-id

###
GET https://your-zentao.example.com/zentao/index.php?m=company&f=browse&t=json&zentaosid=your-session-id

###


GET https://your-zentao.example.com/zentao/api.php/v1/products/1/bugs?page=2&limit=100
Content-Type: 'application/json',
Token: your-token-here
